mainModule.constant("moduleConstants", {
	anonymousUserCaption: "Авторизуватись",
	authorizeSuccessCaption: "User has been authorized",
	authorizeNotSuccessCaption: "User has not been authorized",
	userNotFoundCaption: "User was not found",
	getUserSuccessCaption: "Get user success",
	getUserNotSuccessCaption: "Get user not success",
	getUsersSuccessCaption: "Get users success",
	getUsersNotSuccessCaption: "Get users no success",
	closedSessionMeesage: "Session has been closed",
	loginPath: "/login",
	settingsPath: "/settings",
	myApplicationsPath: "/my_applications",
	homePath: "/home",
	cooperationApplicationCreatingSuccess: "Ваша заявка прийнята",
	emptyFormValue: "не вказано",
	callFeedbackAccepted: "Ваша заявка прийнята",
	deleteTaskConfirmation: "Ви дійсно хочете видалити задачу?",
	userInfoCaption: "Інформація про користувача:",
	invalidPictureFormat: "Картинки повинні бути у форматі jpg, jpeg, png",
	pictureSizeLimitMb: 2,
	pictureSizeInvalid: "Розмір картинки повинен бути не більше {0} МБ",
	notFoundPath: "/404",
	acceptTaskConfirmation: "Ви дійсно хочете прийняти заявку?",
	deleteApplicationConfirmation: "Ви дійсно хочете видалити заявку?",
	deletingInfoSuccess: "Заявка була видалена",
	accountsPath: "/accounts",
	deleteUserConfirmation: "Ви дійсно хочете видалити користувача?",
	pageRowsCount: 5,
	sliderMinRangeValue: 0,
	sliderMaxRangeValue: 30,
	sessionUserIdNotFound: "Потрібна авторизація",
	emptyTextValue: "Не вказано",
	updateDateApplicationConfirm: "Ви дійсно хочете обновити дату заявки?",
	applicationDateUpdatedSuccess: "Дата заявка обновлена",
	editApplicationCaption: "Редагування заявки",
	applicationTrashAddedInfo: "Заявка додана в корзину",
	googleMapsKey: "AIzaSyB51SUDbv8WOYS9yNLniL1DjWNH174A2cU",
	uploadPictureSuccess: "Картинка завантажена",
	internalErrorCaption: "Внутрішня помилка",
    notifyWindowDelay: 1000
});